### ISSUE TITLE
Github Readme Tooltip Example Image is broken

### ISSUE THREAD

**Issue by RafaelStavale** [suspectz/Corruption-Tooltips#10]
As stated in the title., link is broken returning the message ```Non-Image content-type returned```

[Tooltip Example]https://camo.githubusercontent.com/424653aa4902ce632d3fa2d52ca17146dae0b539/68747470733a2f2f6d656469612e666f72676563646e2e6e65742f6174746163686d656e74732f3237372f3935312f776f777363726e73686f745f3032303632305f3233323730382e6a7067)

**Comment by suspectz** [comment]
Thanks, I was trying to load direct from curse, but looks like they block it.
