### ISSUE TITLE
Summary not working

### ISSUE THREAD

**Issue by ShiinaScripts** [suspectz/Corruption-Tooltips#17]
My friend has it working but I cannot make it work
Here's what I mean https://i.imgur.com/50XSakE.jpg

We have the same setting but my equipped corruptions are not displayed here
https://i.imgur.com/ZVmbOd7.png

**Comment by VJNap** [comment]
I'm having the same issue. I confirmed that it's happening due to addon interference by disabling all of other addons to find that it showed up properly by itself. I haven't figured out which addon is causing the interference.

**Comment by VJNap** [comment]
I've determined (at least in the case of my addons list) that the afk addon Narcissus is responsible for removing the summary. I'm assuming this has to do with the fact that Narcissus also access corruption data, and thus causes a conflict, but there doesn't seem to be any way to adjust Narcissus to remove the conflict without completely disabling it.

**Comment by suspectz** [comment]
Hi, This was a known issue. It's fixed for 1.8 which I should release once I get some other bits worked out.

Thanks!
