### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Diablolock** [suspectz/Corruption-Tooltips#28]
Hi, first of all thx for this addon.

I'd like to suggest  anew future just as like this WA: https://wago.io/XsOUJBjhP

Note that it tells the rank on the corrupted items.

Thx in advance.

**Comment by suspectz** [comment]
This will be coming in 1.8.3. You can download the master here to try it in advance. Let me know if you see any issues. Thanks in advance.

**Comment by suspectz** [comment]
This has now been released.
