### ISSUE TITLE
New feature - Vendor corruption rank tooltip

### ISSUE THREAD

**Issue by Hudemehudu** [suspectz/Corruption-Tooltips#29]
With the Corruption Vendor Hotfix there are any corruption to buy now.
Is it possible to implement a funtion to show the rank on any vendor Item?

Thx for your work

**Comment by Natlyz** [comment]
I like this idea. I came here to suggest the same actually.

**Comment by suspectz** [comment]
Yeah, I already got it working for the next version (you can download, test from the zip of master if you want), I just haven't released as I was wondering about how possible it was to add the icon to the buttons too. That combined with the other request for the rank number would make it trivial to spot what to buy I think. I just don't have the time at the moment to add that functionality in.

I also created my own table of vendor items to corruption lookup, and I'm not convinced on the accuracy yet and didn't want people to get annoyed if I got it wrong.

Any assistance would be appreciated.

**Comment by Humwq** [comment]
在当前的售卖列表中，3级暮光毁灭没有显示等级。
TR
In the current sale list, three Twilight destruction did not show level.

**Comment by suspectz** [comment]
> 在当前的售卖列表中，3级暮光毁灭没有显示等级。
> TR
> In the current sale list, three Twilight destruction did not show level.

This has been fixed in the last commit. Thanks for the report.

**Comment by suspectz** [comment]
This will be coming in 1.8.3. You can download the master here to try it in advance. Let me know if you see any issues. Thanks in advance.

**Comment by suspectz** [comment]
This has now been released.
