### ISSUE TITLE
zhCN.lua and Rank.lua

### ISSUE THREAD

**Issue by XnPhy09** [suspectz/Corruption-Tooltips#3]
if GetLocale() ~= "zhCN" then return end
L["Corruption"] = "腐蚀术"
L["Avoidant"] = "闪避者"
L["Expedient"] = "权宜之计"
L["Masterful"] = "娴熟"
L["Severe"] = "暴戾"
L["Versatile"] = "多才多艺"
L["Siphoner"] = "虹吸者"
L["Strikethrough"] = "击穿"
L["Racing Pulse"] = "急速脉搏"
L["Deadly Momentum"] = "致命之势"
L["Surging Vitality"] = "活力涌动"
L["Honed Mind"] = "磨砺心灵"
L["Echoing Void"] = "虚空回响"
L["Infinite Stars"] = "无尽之星"
L["Ineffable Truth"] = "不可言喻的真相"
L["Twilight Devastation"] = "暮光毁灭"
L["Twisted Appendage"] = "扭曲的附肢"
L["Void Ritual"] = "虚空仪式"
L["Gushing Wound"] = "龟裂创伤"
L["Glimpse of Clarity"] = "须臾洞察"
L["Searing Flames"] = "灼热烈焰"
L["Obsidian Skin"] = "黑曜石之肤"
L["Devour Vitality"] = "吞噬活力"
L["Whispered Truths"] = "低语真相"
L["Flash of Insight"] = "灵光一闪"
L["I"] = "1 级"
L["II"] = "2 级"
L["III"] = "3 级"
L[""] = ""

**Comment by XnPhy09** [comment]
and Rank.lua

R = {
    ["6455"] = {L["Avoidant"], L["I"], 315607},
    ["6483"] = {L["Avoidant"], L["I"], 315607},
    ["6460"] = {L["Avoidant"], L["II"], 315608},
    ["6484"] = {L["Avoidant"], L["II"], 315608},
    ["6465"] = {L["Avoidant"], L["III"], 315609},
    ["6485"] = {L["Avoidant"], L["III"], 315609},
    ["6455"] = {L["Expedient"], L["I"], 315544},
    ["6474"] = {L["Expedient"], L["I"], 315544},
    ["6460"] = {L["Expedient"], L["II"], 315545},
    ["6475"] = {L["Expedient"], L["II"], 315545},
    ["6465"] = {L["Expedient"], L["III"], 315546},
    ["6476"] = {L["Expedient"], L["III"], 315546},
    ["6455"] = {L["Masterful"], L["I"], 315529},
    ["6471"] = {L["Masterful"], L["I"], 315529},
    ["6460"] = {L["Masterful"], L["II"], 315530},
    ["6472"] = {L["Masterful"], L["II"], 315530},
    ["6465"] = {L["Masterful"], L["III"], 315531},
    ["6473"] = {L["Masterful"], L["III"], 315531},
    ["6455"] = {L["Severe"], L["I"], 315554},
    ["6480"] = {L["Severe"], L["I"], 315554},
    ["6460"] = {L["Severe"], L["II"], 315557},
    ["6481"] = {L["Severe"], L["II"], 315557},
    ["6465"] = {L["Severe"], L["III"], 315558},
    ["6482"] = {L["Severe"], L["III"], 315558},
    ["6455"] = {L["Versatile"], L["I"], 315549},
    ["6477"] = {L["Versatile"], L["I"], 315549},
    ["6460"] = {L["Versatile"], L["II"], 315552},
    ["6478"] = {L["Versatile"], L["II"], 315552},
    ["6465"] = {L["Versatile"], L["III"], 315553},
    ["6479"] = {L["Versatile"], L["III"], 315553},
    ["6455"] = {L["Siphoner"], L["I"], 315590},
    ["6493"] = {L["Siphoner"], L["I"], 315590},
    ["6460"] = {L["Siphoner"], L["II"], 315591},
    ["6494"] = {L["Siphoner"], L["II"], 315591},
    ["6465"] = {L["Siphoner"], L["III"], 315592},
    ["6495"] = {L["Siphoner"], L["III"], 315592},
    ["6455"] = {L["Strikethrough"], L["I"], 315277},
    ["6437"] = {L["Strikethrough"], L["I"], 315277},
    ["6460"] = {L["Strikethrough"], L["II"], 315281},
    ["6438"] = {L["Strikethrough"], L["II"], 315281},
    ["6465"] = {L["Strikethrough"], L["III"], 315282},
    ["6439"] = {L["Strikethrough"], L["III"], 315282},
    ["6555"] = {L["Racing Pulse"], L["I"], 318266},
    ["6559"] = {L["Racing Pulse"], L["II"], 318492},
    ["6560"] = {L["Racing Pulse"], L["III"], 318496},
    ["6556"] = {L["Deadly Momentum"], L["I"], 318268},
    ["6561"] = {L["Deadly Momentum"], L["II"], 318493},
    ["6562"] = {L["Deadly Momentum"], L["III"], 318497},
    ["6558"] = {L["Surging Vitality"], L["I"], 318270},
    ["6565"] = {L["Surging Vitality"], L["II"], 318495},
    ["6566"] = {L["Surging Vitality"], L["III"], 318499},
    ["6557"] = {L["Honed Mind"], L["I"], 318269},
    ["6563"] = {L["Honed Mind"], L["II"], 318494},
    ["6564"] = {L["Honed Mind"], L["III"], 318498},
    ["6549"] = {L["Echoing Void"], L["I"], 318280},
    ["6550"] = {L["Echoing Void"], L["II"], 318485},
    ["6551"] = {L["Echoing Void"], L["III"], 318486},
    ["6552"] = {L["Infinite Stars"], L["I"], 318274},
    ["6553"] = {L["Infinite Stars"], L["II"], 318487},
    ["6554"] = {L["Infinite Stars"], L["III"], 318488},
    ["6547"] = {L["Ineffable Truth"], L["I"], 318303},
    ["6548"] = {L["Ineffable Truth"], L["II"], 318484},
    ["6537"] = {L["Twilight Devastation"], L["I"], 318276},
    ["6538"] = {L["Twilight Devastation"], L["II"], 318477},
    ["6539"] = {L["Twilight Devastation"], L["III"], 318478},
    ["6543"] = {L["Twisted Appendage"], L["I"], 318481},
    ["6544"] = {L["Twisted Appendage"], L["II"], 318482},
    ["6545"] = {L["Twisted Appendage"], L["III"], 318483},
    ["6540"] = {L["Void Ritual"], L["I"], 318286},
    ["6541"] = {L["Void Ritual"], L["II"], 318479},
    ["6542"] = {L["Void Ritual"], L["III"], 318480},
    ["6573"] = {L["Gushing Wound"], L[""], 318272},
    ["6546"] = {L["Glimpse of Clarity"], L[""], 318239},
    ["6571"] = {L["Searing Flames"], L[""], 318293},
    ["6572"] = {L["Obsidian Skin"], L[""], 316651},
    ["6567"] = {L["Devour Vitality"], L[""], 318294},
    ["6568"] = {L["Whispered Truths"], L[""], 316780},
    ["6570"] = {L["Flash of Insight"], L[""], 318299},
    ["6569"] = {L["Lash of the Void"], L[""], 317290},
}

**Comment by suspectz** [comment]
Hi. Are you reporting that the latest version is not getting proper spell names from the server - or is this patch against an earlier version?

**Comment by XnPhy09** [comment]
just for  zhCN Locales file

**Comment by XnPhy09** [comment]
u can update this files to new version.
