### ISSUE TITLE
Not working and throwing an error.

### ISSUE THREAD

**Issue by PaulVlahosCS** [suspectz/Corruption-Tooltips#4]
40x ...aceCorruptionTooltips\CorruptionTooltips-1.5.2.lua:95: bad argument #2 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:95: in function `Append'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:62: in function `CreateTooltip'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:106: in function <...aceCorruptionTooltips\CorruptionTooltips.lua:105>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:499: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:493>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:425: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419>
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML\PaperDollFrame.lua"]:1684: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "+570 Strength"
(*temporary) = nil
(*temporary) = "string expected, got nil"

Seems to be a conflict between a library in the Undermmine Journal addon and this one if I had to guess.

**Comment by PaulVlahosCS** [comment]
Turned off any mentioned addons in the errors and it still doesn't work properly. Doesn't seem to be a conflict though. 

23x ...aceCorruptionTooltips\CorruptionTooltips-1.5.2.lua:95: bad argument #2 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:95: in function `Append'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:62: in function `CreateTooltip'
[string "@CorruptionTooltips\CorruptionTooltips-1.5.2.lua"]:106: in function <...aceCorruptionTooltips\CorruptionTooltips.lua:105>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1413: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "+760 Strength"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by suspectz** [comment]
I think something may be messing with the translations I have. But I'm updating to using AceLocale instead of my own code, so that might fix it.

**Comment by suspectz** [comment]
Can you confirm if this works with 1.6 or later? I've swapped the translation over as advised above, and it's probably not an issue anymore.

**Comment by PaulVlahosCS** [comment]
1.6 looks to have fixed it. Thank you.
