### ISSUE TITLE
"Show summary on the corruption tooltip" does not seem to be displayed every time

### ISSUE THREAD

**Issue by BlueNightSky** [suspectz/Corruption-Tooltips#6]
The function of "Show summary on the corruption tooltip" does not seem to be displayed every time, it is displayed when you first log in, and it disappears when you open the character window again ... don't know why...

By the way, here is an updated zhTW translation:
L["Corruption"] = "腐化"
L["I"] = "1階"
L["II"] = "2階"
L["III"] = "3階"

--config
L["Append to corruption stat"] = "附加在腐化屬性"
L["Use the new style tooltip."] = "使用新型態提示。"
L["Show summary on the corruption tooltip"] = "在腐化提示上顯示概要"
L["List your corruptions in the eye tooltip in the character screen."] = "在角色視窗的眼睛提示中列出您的腐化。"
L["Display in English"] = "顯示為英文"
L["Don't translate the corruption effect names."] = "不要翻譯腐化特效的名稱。"

**Comment by suspectz** [comment]
I've updated the translations. The display buy may have been related to a config issue, which I've corrected. Let me know if it's sorted for you.

**Comment by BlueNightSky** [comment]
After installing version 1.6.2, everything seems to be working.
