### ISSUE TITLE
icon not in line

### ISSUE THREAD

**Issue by WeijieH** [suspectz/Corruption-Tooltips#7]
See screenshot, can you add an option to remove icon from the tooltip?
![Snipaste_2020-02-14_10-20-36](https://user-images.githubusercontent.com/16510655/74543711-db461e80-4f13-11ea-97e5-7265407d3fab.png)

**Comment by suspectz** [comment]
Please try 1.6.3 and let me know if that fixes it.

**Comment by WeijieH** [comment]
The new version fixed this issue, thanks for the quick update!
